FROM shawnlewis/ml-docker

COPY keyboard /etc/default/keyboard

RUN apt-get update \
    && apt-get install -y \
    zlib1g-dev \
    xvfb

RUN pip --no-cache-dir install \
    tabulate \
    gym
RUN pip --no-cache-dir install gym[all]
